"""
Discovery Agent
===============

Searches Semantic Scholar using each keyword cluster generated by the
Topic Decomposition agent. Deduplicates results by paperId and caps the
total at max_total_papers to control downstream LLM cost.

Uses the agent loop with the search_papers tool so the LLM can choose
which queries to run and adapt if a query returns too few results.
"""

from __future__ import annotations

import json

from loguru import logger

from src.core.agent import run_agent_loop
from src.core.errors import safe_exception_summary
from src.core.state import PipelineState
from src.llm.providers import LLMProvider
from src.tools.semantic_scholar import SEARCH_PAPERS_TOOL, search_papers

SYSTEM_PROMPT = """You are a research discovery agent. Your job is to find relevant academic papers
on Semantic Scholar for a given set of keyword clusters.

For each cluster you are given, call the search_papers tool with each of the cluster's keywords.
After collecting all results, respond with a JSON summary indicating how many papers you found.

Be thorough — run a search for every keyword in every cluster.
"""


def run(
    state: PipelineState,
    provider: LLMProvider,
    results_per_query: int = 20,
    max_total_papers: int = 80,
    max_iterations: int = 10,
) -> PipelineState:
    """
    Run the Discovery agent and update state.papers_raw.

    This function bypasses the agent loop for efficiency: it calls the
    Semantic Scholar API directly for each keyword, then optionally uses
    the LLM to rank or filter if desired. Direct API calls are faster and
    cheaper than routing every search through the LLM.

    Parameters
    ----------
    state : PipelineState
        Current pipeline state. Reads state.keyword_clusters.
    provider : LLMProvider
        The configured LLM provider (not used for direct search mode).
    results_per_query : int
        How many results to request per keyword search.
    max_total_papers : int
        Hard cap on total unique papers collected.

    Returns
    -------
    PipelineState
        Updated state with papers_raw populated.
    """
    if not state.keyword_clusters:
        raise ValueError("[Discovery] keyword_clusters is empty — run TopicDecomposition first.")

    logger.info(f"[Discovery] Starting search over {len(state.keyword_clusters)} clusters.")

    seen_ids: set[str] = set()
    all_papers: list[dict] = []

    for cluster in state.keyword_clusters:
        theme = cluster.theme
        keywords = cluster.keywords
        logger.info(f"[Discovery] Cluster: {theme!r} — {len(keywords)} keyword(s)")

        for keyword in keywords:
            if len(all_papers) >= max_total_papers:
                logger.info(f"[Discovery] Reached paper cap ({max_total_papers}). Stopping search.")
                break

            remaining = max_total_papers - len(all_papers)
            fetch_limit = min(results_per_query, remaining)

            try:
                papers = search_papers(query=keyword, limit=fetch_limit)
            except Exception as exc:
                msg = (
                    f"[Discovery] Search failed for keyword {keyword!r}: "
                    f"{safe_exception_summary(exc)}"
                )
                logger.warning(msg)
                state.add_error(msg)
                continue

            new_count = 0
            for paper in papers:
                paper_id = paper.get("paperId")
                if not paper_id or paper_id in seen_ids:
                    continue
                if not paper.get("title"):
                    continue
                seen_ids.add(paper_id)
                # Tag which cluster found this paper
                paper["_source_cluster"] = theme
                all_papers.append(paper)
                new_count += 1

            logger.debug(
                f"[Discovery]   keyword={keyword!r}: {len(papers)} results, "
                f"{new_count} new (total so far: {len(all_papers)})"
            )

        if len(all_papers) >= max_total_papers:
            break

    logger.info(f"[Discovery] Collected {len(all_papers)} unique papers.")
    state.papers_raw = all_papers
    return state


def run_with_agent_loop(
    state: PipelineState,
    provider: LLMProvider,
    max_iterations: int = 15,
) -> PipelineState:
    """
    Alternative: run Discovery via the agent loop (LLM drives the searches).

    Useful for exploring topics where the LLM can adaptively refine queries
    based on early results. Slower and uses more tokens than the direct mode.

    Parameters
    ----------
    state : PipelineState
    provider : LLMProvider
    max_iterations : int

    Returns
    -------
    PipelineState
    """
    clusters_json = json.dumps(
        [cluster.model_dump() for cluster in state.keyword_clusters], indent=2
    )
    user_message = (
        f"Search for papers across these keyword clusters:\n\n{clusters_json}\n\n"
        "Use the search_papers tool for each keyword. "
        "When done, respond with: DONE"
    )

    run_agent_loop(
        system_prompt=SYSTEM_PROMPT,
        tools=[SEARCH_PAPERS_TOOL],
        initial_messages=[{"role": "user", "content": user_message}],
        provider=provider,
        max_iterations=max_iterations,
    )

    # Note: in this mode the agent loop calls the real search_papers function
    # via the tool, but results are not automatically captured into state.
    # This mode is provided as a reference; the direct mode (run()) is preferred.
    logger.warning("[Discovery] run_with_agent_loop: paper results are not captured into state in this mode.")
    return state
